### ISSUE TITLE
Running the script

### ISSUE THREAD

**Issue by dannymichel** [davea/applemusicscrobbler#1]
Honestly, i forget how to install/run python scripts.
How do we run this?

**Comment by dannymichel** [comment]
```
Downloads cd applemusicscrobbler
➜  applemusicscrobbler git:(master) pip install -r requirements.txt
Collecting pyobjc-framework-ScriptingBridge==3.0.4 (from -r requirements.txt (line 1))
  Downloading pyobjc-framework-ScriptingBridge-3.0.4.tar.gz
Collecting pylast (from -r requirements.txt (line 2))
  Downloading pylast-1.6.0.tar.gz (41kB)
    100% |████████████████████████████████| 51kB 3.4MB/s 
Collecting pyobjc-core>=3.0.4 (from pyobjc-framework-ScriptingBridge==3.0.4->-r requirements.txt (line 1))
  Downloading pyobjc-core-3.1.1.tar.gz (2.2MB)
    100% |████████████████████████████████| 2.2MB 614kB/s 
Collecting pyobjc-framework-Cocoa>=3.0.4 (from pyobjc-framework-ScriptingBridge==3.0.4->-r requirements.txt (line 1))
  Downloading pyobjc-framework-Cocoa-3.1.1.tar.gz (3.6MB)
    100% |████████████████████████████████| 3.6MB 369kB/s 
Requirement already satisfied (use --upgrade to upgrade): six in /usr/local/lib/python2.7/site-packages (from pylast->-r requirements.txt (line 2))
Building wheels for collected packages: pyobjc-framework-ScriptingBridge, pylast, pyobjc-core, pyobjc-framework-Cocoa
  Running setup.py bdist_wheel for pyobjc-framework-ScriptingBridge ... done
  Stored in directory: /Users/danny/Library/Caches/pip/wheels/03/b0/02/2ca95fd60d9e6ff7cc59eeda394b5a377f039c1c91754cb42a
  Running setup.py bdist_wheel for pylast ... done
  Stored in directory: /Users/danny/Library/Caches/pip/wheels/8f/9a/e7/3ff54cc4faa6c205f58473c6bd23021863b155d94b7ba1b5d4
  Running setup.py bdist_wheel for pyobjc-core ... done
  Stored in directory: /Users/danny/Library/Caches/pip/wheels/b3/20/e9/a544cd1dea3b54b24e558c298bf3d29c407f83dc2aaa29108d
  Running setup.py bdist_wheel for pyobjc-framework-Cocoa ... done
  Stored in directory: /Users/danny/Library/Caches/pip/wheels/68/51/25/895ba5c7194b7ea57105dd3831ff5c10d0e940018a97bb0ce3
Successfully built pyobjc-framework-ScriptingBridge pylast pyobjc-core pyobjc-framework-Cocoa
Installing collected packages: pyobjc-core, pyobjc-framework-Cocoa, pyobjc-framework-ScriptingBridge, pylast
Successfully installed pylast-1.6.0 pyobjc-core-3.1.1 pyobjc-framework-Cocoa-3.1.1 pyobjc-framework-ScriptingBridge-3.0.4
➜  applemusicscrobbler git:(master) sudo pip install -r requirements.txt
Password:
The directory '/Users/danny/Library/Caches/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/Users/danny/Library/Caches/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Requirement already satisfied (use --upgrade to upgrade): pyobjc-framework-ScriptingBridge==3.0.4 in /usr/local/lib/python2.7/site-packages (from -r requirements.txt (line 1))
Requirement already satisfied (use --upgrade to upgrade): pylast in /usr/local/lib/python2.7/site-packages (from -r requirements.txt (line 2))
Requirement already satisfied (use --upgrade to upgrade): pyobjc-framework-Cocoa>=3.0.4 in /usr/local/lib/python2.7/site-packages (from pyobjc-framework-ScriptingBridge==3.0.4->-r requirements.txt (line 1))
Requirement already satisfied (use --upgrade to upgrade): pyobjc-core>=3.0.4 in /usr/local/lib/python2.7/site-packages (from pyobjc-framework-ScriptingBridge==3.0.4->-r requirements.txt (line 1))
Requirement already satisfied (use --upgrade to upgrade): six in /usr/local/lib/python2.7/site-packages (from pylast->-r requirements.txt (line 2))
➜  applemusicscrobbler git:(master) python scrobbler.py
Traceback (most recent call last):
  File "scrobbler.py", line 4, in <module>
    from configparser import ConfigParser
ImportError: No module named configparser
➜  applemusicscrobbler git:(master) sudo python scrobbler.py
Traceback (most recent call last):
  File "scrobbler.py", line 4, in <module>
    from configparser import ConfigParser
ImportError: No module named configparser
➜  applemusicscrobbler git:(master) 

```
